"""add user role

Revision ID: 6979f2568ccd
Revises: bfaa30e2ea0a
Create Date: 2026-04-27 13:50:15.781008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6979f2568ccd'
down_revision: Union[str, Sequence[str], None] = 'bfaa30e2ea0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_token_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_token_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(50), server_default="user", nullable=False))
    op.alter_column('users', 'role', server_default=None)
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_token_id'), 'refresh_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
