"""add lifecycle timestamps to batches

Revision ID: 24225d6aedee
Revises: d461a807851e
Create Date: 2026-05-01 11:37:20.503513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24225d6aedee'
down_revision: Union[str, Sequence[str], None] = 'd461a807851e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'completed_at')
    # ### end Alembic commands ###
