"""create batches table

Revision ID: d461a807851e
Revises: 
Create Date: 2026-04-28 20:30:34.888629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd461a807851e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('planned_quantity', sa.Integer(), nullable=False),
    sa.Column('produced_quantity', sa.Integer(), nullable=False),
    sa.Column('accepted_quantity', sa.Integer(), nullable=False),
    sa.Column('defect_quantity', sa.Integer(), nullable=False),
    sa.Column('length_target', sa.Float(), nullable=False),
    sa.Column('width_target', sa.Float(), nullable=False),
    sa.Column('height_target', sa.Float(), nullable=False),
    sa.Column('length_tolerance', sa.Float(), nullable=False),
    sa.Column('width_tolerance', sa.Float(), nullable=False),
    sa.Column('height_tolerance', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('created', 'in_progress', 'completed', 'cancelled', name='batchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('accepted_quantity + defect_quantity <= produced_quantity', name='check_total_quality_counts_valid'),
    sa.CheckConstraint('accepted_quantity >= 0', name='check_accepted_quantity_non_negative'),
    sa.CheckConstraint('defect_quantity >= 0', name='check_defect_quantity_non_negative'),
    sa.CheckConstraint('planned_quantity > 0', name='check_planned_quantity_positive'),
    sa.CheckConstraint('produced_quantity <= planned_quantity', name='check_produced_not_exceed_planned'),
    sa.CheckConstraint('produced_quantity >= 0', name='check_produced_quantity_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_batch_number'), 'batches', ['batch_number'], unique=True)
    op.create_index(op.f('ix_batches_created_at'), 'batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_batches_id'), 'batches', ['id'], unique=False)
    op.create_index(op.f('ix_batches_product_name'), 'batches', ['product_name'], unique=False)
    op.create_index(op.f('ix_batches_status'), 'batches', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batches_status'), table_name='batches')
    op.drop_index(op.f('ix_batches_product_name'), table_name='batches')
    op.drop_index(op.f('ix_batches_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_created_at'), table_name='batches')
    op.drop_index(op.f('ix_batches_batch_number'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
