"""create parts table

Revision ID: f80f0635808c
Revises: 24225d6aedee
Create Date: 2026-05-02 00:35:54.571712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80f0635808c'
down_revision: Union[str, Sequence[str], None] = '24225d6aedee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('length_actual', sa.Float(), nullable=False),
    sa.Column('width_actual', sa.Float(), nullable=False),
    sa.Column('height_actual', sa.Float(), nullable=False),
    sa.Column('is_defective', sa.Boolean(), nullable=False),
    sa.Column('defect_reason', sa.Enum('LENGTH_EXCEEDS_TOLERANCE', 'WIDTH_EXCEEDS_TOLERANCE', 'HEIGHT_EXCEEDS_TOLERANCE', 'SURFACE_DAMAGE', 'GEOMETRY_DISTORTION', 'SENSOR_ERROR', 'MANUAL_REJECTION', name='defectreason'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_defective = FALSE AND defect_reason IS NULL) OR (is_defective = TRUE)', name='check_defect_reason_consistency'),
    sa.CheckConstraint('height_actual > 0', name='check_height_actual_positive'),
    sa.CheckConstraint('length_actual > 0', name='check_length_actual_positive'),
    sa.CheckConstraint('width_actual > 0', name='check_width_actual_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_batch_id'), 'parts', ['batch_id'], unique=False)
    op.create_index(op.f('ix_parts_created_at'), 'parts', ['created_at'], unique=False)
    op.create_index(op.f('ix_parts_defect_reason'), 'parts', ['defect_reason'], unique=False)
    op.create_index(op.f('ix_parts_id'), 'parts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parts_id'), table_name='parts')
    op.drop_index(op.f('ix_parts_defect_reason'), table_name='parts')
    op.drop_index(op.f('ix_parts_created_at'), table_name='parts')
    op.drop_index(op.f('ix_parts_batch_id'), table_name='parts')
    op.drop_table('parts')
    # ### end Alembic commands ###
