from enum import Enum


class NotificationSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class NotificationEventType(str, Enum):
    PART_CREATED = "PART_CREATED"
    PART_UPDATED = "PART_UPDATED"
    PART_DELETED = "PART_DELETED"
    PART_DEFECTIVE_DETECTED = "PART_DEFECTIVE_DETECTED"

    BATCH_CREATED = "BATCH_CREATED"
    BATCH_UPDATED = "BATCH_UPDATED"
    BATCH_COMPLETED = "BATCH_COMPLETED"
    BATCH_CANCELLED = "BATCH_CANCELLED"
